[project]
name = "spotify2yt"
version = "2.0"
description = "CLI tool to migrate playlists between Spotify and YouTube Music"
requires-python = ">=3.10"
dependencies = [
    "typer",
    "spotipy",
    "ytmusicapi",
    "python-dotenv",
    "rich"
]

[build-system]
requires = []
build-backend = "setuptools.build_meta"