"""YouTube Music API client."""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any

from tqdm import tqdm
from ytmusicapi import YTMusic
from ytmusicapi.auth.oauth import OAuthCredentials

from .matching import (
    SONG_MATCH_THRESHOLD,
    VIDEO_MATCH_THRESHOLD,
    Track,
    score_match,
)

logger = logging.getLogger(__name__)

_client: YTMusic | None = None

# Auth files generated by the official setup flows, probed in order:
#   "uv run ytmusicapi browser" -> browser.json / headers_auth.json
#   "uv run ytmusicapi oauth"   -> oauth.json / headers_auth.json
_DEFAULT_AUTH_FILES = ("browser.json", "headers_auth.json", "oauth.json")

# Search stages: official songs are preferred; videos are a fallback for
# tracks that only exist as uploads (but demand a stricter score).
_SEARCH_STAGES: tuple[tuple[str, float], ...] = (
    ("songs", SONG_MATCH_THRESHOLD),
    ("videos", VIDEO_MATCH_THRESHOLD),
)

_CANDIDATES_PER_SEARCH = 5


def _auth_file() -> str:
    """Locate the YouTube Music auth file.

    Resolution order: the ``YTMUSIC_AUTH_FILE`` environment variable, then
    the default filenames generated by ``ytmusicapi``'s setup flows.
    """
    configured = os.getenv("YTMUSIC_AUTH_FILE")
    if configured:
        if not Path(configured).is_file():
            raise RuntimeError(f"YouTube Music auth file not found: {configured}")
        return configured

    for name in _DEFAULT_AUTH_FILES:
        if Path(name).is_file():
            logger.debug("Using YouTube Music auth file: %s", name)
            return name

    raise RuntimeError(
        "No YouTube Music auth file found. Create one with "
        "'uv run ytmusicapi browser' (browser.json) or 'uv run ytmusicapi oauth' "
        "(headers_auth.json), or point YTMUSIC_AUTH_FILE at your auth file."
    )


def _oauth_credentials() -> OAuthCredentials | None:
    """Build OAuth credentials from the environment when using an OAuth token.

    Token files created by ``ytmusicapi oauth`` only store the tokens, not the
    client credentials, so they must be supplied again to refresh the token.
    """
    client_id = os.getenv("YTMUSIC_CLIENT_ID")
    client_secret = os.getenv("YTMUSIC_CLIENT_SECRET")
    if not client_id and not client_secret:
        return None
    if not client_id or not client_secret:
        raise RuntimeError(
            "Set both YTMUSIC_CLIENT_ID and YTMUSIC_CLIENT_SECRET so the "
            "OAuth token can be refreshed."
        )
    return OAuthCredentials(client_id, client_secret)


def _get_client() -> YTMusic:
    """Build the YouTube Music client lazily so the CLI works without auth."""
    global _client
    if _client is None:
        auth_path = _auth_file()
        is_oauth_token = "refresh_token" in json.loads(Path(auth_path).read_text())
        _client = YTMusic(
            auth_path,
            oauth_credentials=_oauth_credentials() if is_oauth_token else None,
        )
    return _client


def get_ytmusic_playlist_tracks(playlist_id: str) -> list[str]:
    """Return ``"Artist Title"`` queries for every track of a YouTube Music playlist."""
    playlist = _get_client().get_playlist(playlist_id)

    results: list[str] = []
    for track in playlist.get("tracks", []):
        title = track.get("title", "Unknown Title")
        artists = track.get("artists", [])
        artist = artists[0]["name"] if artists else "Unknown Artist"
        results.append(f"{artist} {title}")

    logger.info("Retrieved %d tracks from playlist %s.", len(results), playlist_id)
    return results


def _candidate_fields(item: dict[str, Any]) -> tuple[str, list[str], float | None]:
    """Extract title, artist names and duration from a search result."""
    title = item.get("title", "")
    artists = [
        artist["name"]
        for artist in item.get("artists") or []
        if isinstance(artist, dict) and artist.get("name")
    ]
    duration = item.get("duration_seconds")
    return title, artists, float(duration) if duration is not None else None


def _best_candidate(
    track: Track, results: list[dict[str, Any]]
) -> tuple[str | None, float]:
    """Return the highest scoring video ID and its score for a list of results."""
    best_id: str | None = None
    best_score = 0.0

    for item in results:
        video_id = item.get("videoId")
        if not video_id:
            continue
        title, artists, duration = _candidate_fields(item)
        score = score_match(track, title, artists, duration)
        if score > best_score:
            best_id, best_score = video_id, score

    return best_id, best_score


def _match_track(track: Track) -> str | None:
    """Search YouTube Music for a track and return the best matching video ID.

    Each stage searches a result category and only accepts a candidate whose
    score clears that stage's threshold. Songs are tried first; videos act as
    a stricter fallback so covers and live versions are avoided.
    """
    client = _get_client()
    fallback: tuple[str, float] | None = None

    for search_filter, threshold in _SEARCH_STAGES:
        try:
            results = client.search(
                track.query, filter=search_filter, limit=_CANDIDATES_PER_SEARCH
            )
        except Exception:  # a single failed search must not abort the transfer
            logger.warning("Search failed for '%s'.", track.query, exc_info=True)
            continue

        video_id, score = _best_candidate(track, results)
        if video_id is None:
            continue

        if score >= threshold:
            logger.debug(
                "Matched '%s' -> %s (score %.2f).", track.title, video_id, score
            )
            return video_id

        if fallback is None or score > fallback[1]:
            fallback = (video_id, score)

    if fallback is not None:
        logger.warning(
            "Low-confidence match (%.2f) for '%s' by %s.",
            fallback[1],
            track.title,
            ", ".join(track.artists),
        )
    else:
        logger.warning(
            "No match found for '%s' by %s.",
            track.title,
            ", ".join(track.artists),
        )
    return None


def search_songs_ytmusic(tracks: list[Track]) -> list[str | None]:
    """Map Spotify tracks to YouTube Music video IDs (``None`` when unmatched)."""
    song_ids: list[str | None] = []

    for track in tqdm(tracks, desc="Matching songs on YouTube Music"):
        song_ids.append(_match_track(track))

    logger.info("Completed search for %d songs.", len(tracks))
    return song_ids


def create_ytmusic_playlist(
    playlist_name: str,
    playlist_privacy: str = "PRIVATE",
    songs_id: list[str] | None = None,
) -> str:
    """Create a playlist and return a success or failure message."""
    if not songs_id:
        return "No songs provided to create playlist."

    _get_client().create_playlist(
        title=playlist_name,
        description="",
        privacy_status=playlist_privacy,
        video_ids=songs_id,
    )
    logger.info("Playlist '%s' created successfully.", playlist_name)
    return f"Playlist '{playlist_name}' was created!"


def get_ytmusic_playlists() -> list[dict[str, str]]:
    """Return the user's playlists as ``{"name": ..., "id": ...}`` entries."""
    playlists = _get_client().get_library_playlists()

    result: list[dict[str, str]] = []
    for playlist in playlists:
        playlist_id = playlist.get("playlistId")
        if playlist_id:
            result.append(
                {
                    "name": playlist.get("title", "Unknown"),
                    "id": playlist_id,
                }
            )

    logger.info("Retrieved %d playlists from YouTube Music library.", len(result))
    return result


def get_ytmusic_playlist_name(playlist_id: str) -> str:
    """Return the name of a YouTube Music playlist."""
    return _get_client().get_playlist(playlist_id).get("title", "Unknown Playlist")


def delete_ytmusic_playlist(playlist_id: str) -> None:
    """Delete a YouTube Music playlist."""
    _get_client().delete_playlist(playlist_id)
    logger.info("Playlist %s deleted.", playlist_id)
